# Site settings
title: MrFriz, le Club d'ultimate frisbee rennais
email: your-email@domain.com
description: "Créé en 2000 par des étudiants de l’INSA, le club d’ultimate de Rennes a progressivement grandi au fil des saisons. Association loi 1901 déclarée en préfecture, le club Mr Friz est affilié à la Fédération Flying Disc France (FFDF). D’une dizaine à l’origine, le nombre de licenciés est monté à plus de 45 en 2011/2012."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
